## Numpy

Numpy 是 Python 中用于科学计算的基本包。 它是一个 Python 库，提供多维数组对象、各种派生对象(如屏蔽数组和矩阵) ，以及用于数组快速操作的各种例程，包括数学、逻辑、形状操作、排序、选择、 i/o、离散傅立叶变换、基本线性代数、基本统计操作、随机模拟等等。

### 版本

In [1]:
import numpy
numpy.__version__

'1.15.4'

### 别名
遵循传统，使用`np`作为别名导入 NumPy ：

In [2]:
import numpy as np

### 数组

Numpy 包的核心是`ndarray`对象，封装了同类数据类型的 n 维数组，通常用别名`array`来表示。

#### 属性

每个`Numpy`数组都拥有如下属性：

- `nidm`：数组维度
- `shape`：维度大小
- `size`：数组大小
- `dtype`：数据类型
- `itemsize`：元素字节大小, 以`bytes`为单位
- `nbytes`：数组字节大小, 以`bytes`为单位

In [3]:
# 创建一个3×3、由[0,10)均匀分布随机整数组成的数值
x = (np.random.randint(0, 10, (3, 3)))
print(x)
print('\nx.ndim:',x.ndim)
print('x.shape:',x.shape)
print('x.size:',x.size)
print('x.dtype:',x.dtype)
print('x.itemsize:',x.itemsize)
print('x.nbytes:',x.nbytes)

[[3 4 9]
 [0 0 6]
 [4 4 3]]

x.ndim: 2
x.shape: (3, 3)
x.size: 9
x.dtype: int32
x.itemsize: 4
x.nbytes: 36


#### 利用列表(list)生成数组

利用```nd.array```从 Pyhon 列表创建数值:

In [4]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

不同于 Python 列表， Numpy 要求数组必须包含同一类型的数据。如果类型不匹配，NumPy 将会向上转换（如果可行）。

In [5]:
x = np.array([1.0, 2, 3.0, 4])
x

array([1., 2., 3., 4.])

如果希望明确设置数组的数据类型，可以用```dtype```变量：

In [6]:
x = np.array([1, 2, 3, 4], dtype=np.float32)
x

array([1., 2., 3., 4.], dtype=float32)

构建多维数组：

In [7]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 利用```Numpy```内置方法创建数值

`np.zeros()`:创建全 0 数值

In [8]:
# 创建一个长度为5的全0数组
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

`np.ones()`:创建全 1 数组

In [9]:
# 创建一个3*3的q全1矩阵
x = np.ones((3,3), dtype=float)
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

`np.eye()`:创建一个单位矩阵

In [10]:
# 创建一个3*3的单位矩阵
x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

`np.full(shape, fill_value)`：创建一个维数为`shape`、值为`fill_value`的数组

In [11]:
# 创建一个维数为3*3、值为2.0的浮点数型数组
x = np.full((3,3), fill_value=2.0)
x

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

序列数组：

- `np.arange(start, stop, step)`：创建一个从`start`到`stop`,步长为`step`的序列数组。
- `np.linspace(start, stop, num=50)`：创建一个从`start`到`stop`,元素个数为`num`的序列数组。

In [12]:
# 创建一个从0到10,步长为2的序列数组
x = np.arange(0, 10, 2)
x

array([0, 2, 4, 6, 8])

In [13]:
# 创建一个从0到10,元素个数为5的序列数组
x = np.linspace(0, 10, 5)
x

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

随机分布数组：

- `np.random.random()`：创建一个由 0 ~ 1 均匀分布生成的随机数组成的数组
- `np.random.normal(loc=0.0, scale=1.0, size=None)`：创建一个由均值为`loc`、方差为`scale`的正态分布生成的随机数组成的数组
- `np.random.randint(low, high=None, size=None)`：创建一个由`low`~`high`均匀分布生成的随机整数组成的数值

In [14]:
# 创建一个3×3、由0~1均匀分布随机数组成的数组
x = np.random.random((3, 3))
x

array([[0.36002842, 0.08519123, 0.4640263 ],
       [0.54155948, 0.43645734, 0.44322506],
       [0.30741928, 0.2057965 , 0.21929336]])

In [15]:
# 创建一个3×3、由均值为0、方差为1的正态分布随机数组成的数组
x = np.random.normal(0, 1, (3, 3))
x

array([[-0.35800332, -0.36553495, -0.62851015],
       [-2.01214244,  0.42221338,  0.25461076],
       [ 0.64228871,  0.28348644,  0.69593449]])

In [16]:
# 创建一个3×3、由[0,10)均匀分布随机整数组成的数值
x = (np.random.randint(0, 10, (3, 3)))
x

array([[3, 6, 0],
       [3, 2, 3],
       [0, 9, 2]])

### 数组操作

#### 基本运算

数组上的运算与 Python 类似，支持 Python 原生的算术运算符，标准的加、减、乘、除都可以使用。

In [17]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


运算符与通用函数的对应关系如下表所示：

| 运算符 | 对应的通用函数  |        描述        |
| :----: | :-------------: | :----------------: |
|+    |     np.add      |      加法运算      |
|-    |   np.subtract   |      减法运算      |
|-    |   np.negative   |      负数运算      |
|   *    |   np.multipy    |      乘法运算      |
|   /    |    np.divide    |      除法运算      |
|   //   | np.floor_divide |    取商除法运算    |
|   **   |    np.power     |      指数运算      |
|   &    |     np.mod      | 取模(余数)除法运算 |

与许多矩阵语言不同，乘法运算符`*`在 Numpy 数组中按元素操作，矩阵运算可以使用`@`操作符(在 python 3.5中)或`dot`函数执行。

In [18]:
A = np.array( [[1,1],
            [0,1]] )
B = np.array( [[2,0],
            [3,4]] )
# 元素操作
print('A * B =\n',A * B)

# 矩阵运算
print('\nA @ B =\n',A @ B)

# 另一种矩阵运算
print('\nA.dot(B) =\n', A.dot(B))

A * B =
 [[2 0]
 [0 4]]

A @ B =
 [[5 4]
 [3 4]]

A.dot(B) =
 [[5 4]
 [3 4]]


#### 索引与切片

In [19]:
# 创建一个3×3、由[0,10)均匀分布随机整数组成的数值
x = (np.random.randint(0, 10, (3, 3)))
print(x)

# 索引
print('\nx[1,1] =',x[1,1])

# 切片
print('x[1:,1:] =\n',x[1:,1:])

[[5 0 5]
 [1 9 6]
 [1 5 1]]

x[1,1] = 9
x[1:,1:] =
 [[9 6]
 [5 1]]


#### 排序

- np.sort(a,  axis=1)：`a`表示要排序的数值，`axis=0`表示按列排序(`axis=1`表示按行排序)

In [20]:
# 创建一个4×6、由[0,10)均匀分布随机整数组成的数值
x = (np.random.randint(0, 10, (4, 6)))
print('x =\n',x)

# 按列排序
print('\nnp.sort(x, axis=0) =\n',np.sort(x, axis=0))

# 按列排序
print('\nnp.sort(x, axis=1) =\n',np.sort(x, axis=1))

x =
 [[7 9 6 2 1 2]
 [9 3 4 5 8 7]
 [4 6 8 1 6 7]
 [5 7 8 6 1 2]]

np.sort(x, axis=0) =
 [[4 3 4 1 1 2]
 [5 6 6 2 1 2]
 [7 7 8 5 6 7]
 [9 9 8 6 8 7]]

np.sort(x, axis=1) =
 [[1 2 2 6 7 9]
 [3 4 5 7 8 9]
 [1 4 6 6 7 8]
 [1 2 5 6 7 8]]


#### 变形

- ```reshape()```方法

In [21]:
# 创建一个3×3、由[0,10)均匀分布随机整数组成的数值
x = (np.random.randint(0, 10, (3, 3)))
print('x =\n',x)
print('\n通过变形获得的行向量:\n', x.reshape((1, 9)))
print('通过变形获得的列向量:\n', x.reshape((9, 1)))

x =
 [[9 3 5]
 [8 7 7]
 [2 7 2]]

通过变形获得的行向量:
 [[9 3 5 8 7 7 2 7 2]]
通过变形获得的列向量:
 [[9]
 [3]
 [5]
 [8]
 [7]
 [7]
 [2]
 [7]
 [2]]



#### 转置

In [22]:
x = (np.random.randint(0, 10, (2, 3)))
print('x =\n',x)
print('\nx.T =\n',x.T)

x =
 [[0 4 0]
 [5 8 6]]

x.T =
 [[0 5]
 [4 8]
 [0 6]]


#### 拼接

- ```np.concatenate((a1, a2, ...), axis=0)```：按垂直(水平`axis=1`)拼接数组元组`(a1, a2, ...)`或数值列表`[a1, a2, ...]`
- ```np.vstack((a1, a2, ...))```：按垂直方向拼接数组元组`(a1, a2, ...)`或数值列表`[a1, a2, ...]`
- ```np.hstack((a1, a2, ...))```：按水平方向拼接数组元组`(a1, a2, ...)`或数值列表`[a1, a2, ...]`

In [23]:
x = np.array([[1,2,3,4],
                  [1,2,3,4]])
x

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [24]:
# 按垂直方向拼接数组x和x
print('通过np.concatenate()方法拼接:\n',np.concatenate((x,x)))
print('通过np.vstack()方法拼接:\n',np.vstack((x,x)))

通过np.concatenate()方法拼接:
 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
通过np.vstack()方法拼接:
 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [25]:
# 按水平方向拼接数值x和x
print('通过np.concatenate()方法拼接:\n',np.concatenate((x,x),axis=1))
print('通过np.vstack()方法拼接:\n',np.hstack((x,x)))

通过np.concatenate()方法拼接:
 [[1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]]
通过np.vstack()方法拼接:
 [[1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]]


#### 拆分

- `np.split(ary, indices_or_sections, axis=0)`：`ary`为要拆分的数值，`indices_or_sections`为拆分节点序列，`axis=0`表示按竖直方向拆分(`axis=1`表示按竖直方向拆分)
- `np.hsplit()`：按水平方向拆分
- `np.vsplit()`：按竖直方向拆分

一维数组：

In [26]:
x = np.arange(9)
print(x)
print(np.split(x,3))
print(np.split(x,[2,5,7]))

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1]), array([2, 3, 4]), array([5, 6]), array([7, 8])]


二维数组：

In [27]:
# 按竖直方向拆分
y = (np.random.randint(0, 10, (3, 3)))
print('通过np.split()方法拆分:\n',np.split(y, 3))
print('通过np.hsplit()方法拆分:\n',np.vsplit(y, 3))

通过np.split()方法拆分:
 [array([[3, 4, 1]]), array([[9, 7, 0]]), array([[0, 0, 8]])]
通过np.hsplit()方法拆分:
 [array([[3, 4, 1]]), array([[9, 7, 0]]), array([[0, 0, 8]])]


In [28]:
# 按水平方向拆分
print('通过np.split()方法拆分:\n',np.split(y, 3, axis=1))
print('通过np.hsplit()方法拆分:\n',np.hsplit(y, 3))

通过np.split()方法拆分:
 [array([[3],
       [9],
       [0]]), array([[4],
       [7],
       [0]]), array([[1],
       [0],
       [8]])]
通过np.hsplit()方法拆分:
 [array([[3],
       [9],
       [0]]), array([[4],
       [7],
       [0]]), array([[1],
       [0],
       [8]])]


### 通用函数

Numpy 提供熟悉的数学函数，例如`sin`，`cos`和`exp`等，在 NumPy 中，这些被称为“通用函数”（`ufunc`）。

In [29]:
x = np.arange(3)
print('x =',x)
print('np.exp(x) =',np.exp(x))
print('np.sqrt(x) =',np.sqrt(x))
print('np.add(x) =',np.add(x,x))

x = [0 1 2]
np.exp(x) = [1.         2.71828183 7.3890561 ]
np.sqrt(x) = [0.         1.         1.41421356]
np.add(x) = [0 2 4]


Numpy 提供了大量的通用函数，详细列表请点击[这里](https://docs.scipy.org/doc/numpy/reference/routines.html#routines)

### 广播

广播是一种强有力的机制，通过它 NumPy 可以使不同大小的矩阵在一起进行数学计算。

In [30]:
a = np.array([[ 0.0, 0.0, 0.0],
               [10.0,10.0,10.0],
               [20.0,20.0,20.0],
               [30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])
a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

想了解更多细节可以点击[这里](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)

### 参考资料

- [Numpy 用户指南](https://docs.scipy.org/doc/numpy/user/index.html)